# Add these at the top of your settings.py
import os
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url

load_dotenv()


"""
Django settings for tfshome project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ah5@oa%*lxibtilj2#y&r_nad9z4j2n%ydw7-mlk!19@+8^xf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'users',
    'goals',
    'tasks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tfshome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tfshome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Replace the DATABASES section of your settings.py with this

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,       # Keeps connections open for better performance
        conn_health_checks=True # Re-opens connections if Neon goes to sleep
    )
}

# Essential for Neon's serverless connection pooler
DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTH_USER_MODEL='users.CustomUser'

# --- CORS Configuration ---

# 1. ALLOWED ORIGINS (The list of domains/ports that are explicitly allowed to make requests)
CORS_ALLOWED_ORIGINS = [
    # Allow the Next.js development server
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    
    # Add your production domain(s) here later:
    # "https://www.your-production-app.com",
]

# 2. ALLOW ALL HEADERS AND METHODS
# This is usually safe for development/API consumption, but can be restricted if necessary.
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_CREDENTIALS=True

from corsheaders.defaults import default_headers
CORS_ALLOW_ALL_HEADERS=list(default_headers) + [
    'authorization',
    'content-type',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 3. ALLOW COOKIES/CREDENTIALS (Necessary for JWT and potentially CSRF/Session management)
CORS_ALLOW_CREDENTIALS = True

SIMPLE_JWT = {
    # 1. Access Token: Set to a very safe, generous amount for local development (e.g., 10 minutes)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    
    # 2. Refresh Token: Keep the default, or slightly longer
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # 7 days is standard and safer than 1

    # Ensure this setting is correct for the serializer we custom-defined
    'TOKEN_OBTAIN_PAIR_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',

    # Optional: If you want to customize token verification/payload (we already did this in our custom serializer)
    # 'AUTH_HEADER_TYPES': ('Bearer',),
    # 'USER_ID_FIELD': 'id',
    # 'USER_ID_CLAIM': 'user_id',
}

#Set up OPENAI API key 
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')