# Generated by Django 5.1.15 on 2025-12-15 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('due_date', models.DateField(blank=True, help_text='The deadline for the task.', null=True, verbose_name='due date')),
                ('effort_estimate', models.PositiveSmallIntegerField(default=3, help_text='Estimated effort required (1=low to 5=high).', verbose_name='effort estimate')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['is_completed', 'due_date', '-created_at'],
            },
        ),
    ]
