# Generated by Django 5.1.15 on 2025-12-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-priority_score', 'due_date', '-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='goals.goal', verbose_name='associated goal'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_prioritized',
            field=models.BooleanField(default=False, help_text='Flag indicating if the task has been processed by the AI engine.', verbose_name='is prioritized'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='AI-calculated score for prioritization.', verbose_name='priority score'),
        ),
    ]
