# Generated by Django 5.1.15 on 2025-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_goal_task_is_prioritized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='The ID of the background process handling the AI scoring.', max_length=255, null=True),
        ),
    ]
