# Generated by Django 5.1.15 on 2025-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance_score',
            field=models.FloatField(default=0.0, help_text='Weighted importance score ∈ [0,1].', verbose_name='importance score'),
        ),
        migrations.AddField(
            model_name='task',
            name='quadrant',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Eisenhower quadrant assignment.', max_length=2, null=True, verbose_name='quadrant'),
        ),
        migrations.AddField(
            model_name='task',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text='Short explanation of prioritization decision.', verbose_name='rationale'),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency_score',
            field=models.FloatField(default=0.0, help_text='Urgency score ∈ [0,1].', verbose_name='urgency score'),
        ),
    ]
