# Generated by Django 5.1.15 on 2026-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_importance_score_task_quadrant_task_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the task was last processed by the AI engine.', null=True, verbose_name='last analyzed at'),
        ),
    ]
