# Generated by Django 5.1.15 on 2025-12-19 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_bills', models.FloatField(default=0.25, help_text='Importance weight for financial and career tasks.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('study', models.FloatField(default=0.25, help_text='Importance weight for education and skill building.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('health', models.FloatField(default=0.25, help_text='Importance weight for physical and mental well-being.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('relationships', models.FloatField(default=0.25, help_text='Importance weight for social and family life.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal Weights',
                'verbose_name_plural': 'Goal Weights',
            },
        ),
    ]
